Netlist(Freeze)
Netlist(Clear)
Netlist(Add,Chassis,CONN1-5)
Netlist(Add,Chassis,CONN4-5)
Netlist(Add,Chassis,CONN5-1)
Netlist(Add,unnamed_net9,TP9-1)
Netlist(Add,unnamed_net9,R12-2)
Netlist(Add,unnamed_net9,CONN10-1)
Netlist(Add,OUT,R12-1)
Netlist(Add,OUT,C10-1)
Netlist(Add,OUT,R10-2)
Netlist(Add,OUT,U10-6)
Netlist(Add,unnamed_net8,R11-2)
Netlist(Add,unnamed_net8,C10-2)
Netlist(Add,unnamed_net8,R10-1)
Netlist(Add,unnamed_net8,U10-2)
Netlist(Add,unnamed_net7,R21-2)
Netlist(Add,unnamed_net7,R20-1)
Netlist(Add,U5SUM:1,R20-2)
Netlist(Add,U5SUM:1,C20-2)
Netlist(Add,U5SUM:1,U20-2)
Netlist(Add,GND,CONN1-2)
Netlist(Add,GND,CONN1-3)
Netlist(Add,GND,CONN4-3)
Netlist(Add,GND,CONN4-2)
Netlist(Add,GND,TP7-1)
Netlist(Add,GND,CONN10-2)
Netlist(Add,GND,C14-2)
Netlist(Add,GND,C13-1)
Netlist(Add,GND,C11-1)
Netlist(Add,GND,C12-2)
Netlist(Add,GND,U10-3)
Netlist(Add,GND,C22-1)
Netlist(Add,GND,C21-2)
Netlist(Add,GND,U20-3)
Netlist(Add,GND,R43-2)
Netlist(Add,GND,R42-1)
Netlist(Add,GND,C45-1)
Netlist(Add,GND,C42-2)
Netlist(Add,GND,C43-1)
Netlist(Add,GND,C44-2)
Netlist(Add,CHASSIS:1,U?-?)
Netlist(Add,CHASSIS:1,CONN40-3)
Netlist(Add,unnamed_net6,TP5-1)
Netlist(Add,unnamed_net6,CONN40-2)
Netlist(Add,unnamed_net6,C41-1)
Netlist(Add,unnamed_net5,TP4-1)
Netlist(Add,unnamed_net5,CONN40-1)
Netlist(Add,unnamed_net5,C40-1)
Netlist(Add,unnamed_net4,R43-1)
Netlist(Add,unnamed_net4,C41-2)
Netlist(Add,unnamed_net4,U40-3)
Netlist(Add,OFFSET,TP2-1)
Netlist(Add,OFFSET,C20-1)
Netlist(Add,OFFSET,U20-6)
Netlist(Add,OFFSET,U40-5)
Netlist(Add,N15V,CONN1-4)
Netlist(Add,N15V,CONN4-4)
Netlist(Add,N15V,TP8-1)
Netlist(Add,N15V,C13-2)
Netlist(Add,N15V,C12-1)
Netlist(Add,N15V,U10-4)
Netlist(Add,N15V,C22-2)
Netlist(Add,N15V,U20-4)
Netlist(Add,N15V,C23-2)
Netlist(Add,N15V,C46-2)
Netlist(Add,N15V,C48-2)
Netlist(Add,N15V,C47-1)
Netlist(Add,N15V,C45-2)
Netlist(Add,N15V,C43-2)
Netlist(Add,N15V,U40-4)
Netlist(Add,P15V,CONN1-1)
Netlist(Add,P15V,CONN4-1)
Netlist(Add,P15V,TP6-1)
Netlist(Add,P15V,C14-1)
Netlist(Add,P15V,C11-2)
Netlist(Add,P15V,U10-7)
Netlist(Add,P15V,C21-1)
Netlist(Add,P15V,U20-7)
Netlist(Add,P15V,C23-1)
Netlist(Add,P15V,C46-1)
Netlist(Add,P15V,C48-1)
Netlist(Add,P15V,C47-2)
Netlist(Add,P15V,C42-1)
Netlist(Add,P15V,C44-1)
Netlist(Add,P15V,U40-7)
Netlist(Add,unnamed_net3,R41-2)
Netlist(Add,unnamed_net3,U40-8)
Netlist(Add,unnamed_net2,R42-2)
Netlist(Add,unnamed_net2,C40-2)
Netlist(Add,unnamed_net2,U40-2)
Netlist(Add,unnamed_net1,R41-1)
Netlist(Add,unnamed_net1,U40-1)
Netlist(Add,SMALL,R11-1)
Netlist(Add,SMALL,R21-1)
Netlist(Add,SMALL,U40-6)
Netlist(Add,SMALL,TP1-1)
Netlist(Sort)
Netlist(Thaw)
ElementList(Start)
ElementList(Need,"CONN1","molex-22-05-3051-mini_5_ra.fp","126-221")
ElementSetAttr("CONN1","device","CONNECTOR_5")
ElementSetAttr("CONN1","manufacturer","unknown")
ElementSetAttr("CONN1","manufacturer_part_number","unknown")
ElementSetAttr("CONN1","vendor","unknown")
ElementSetAttr("CONN1","vendor_part_number","unknown")
ChangePinName("CONN1", 5, "5")
ChangePinName("CONN1", 3, "3")
ChangePinName("CONN1", 1, "1")
ChangePinName("CONN1", 4, "4")
ChangePinName("CONN1", 2, "2")
ElementList(Need,"CONN4","molex-22-05-3051-mini_5_ra.fp","126-220")
ElementSetAttr("CONN4","device","CONNECTOR_5")
ElementSetAttr("CONN4","manufacturer","unknown")
ElementSetAttr("CONN4","manufacturer_part_number","unknown")
ElementSetAttr("CONN4","vendor","unknown")
ElementSetAttr("CONN4","vendor_part_number","unknown")
ChangePinName("CONN4", 5, "5")
ChangePinName("CONN4", 3, "3")
ChangePinName("CONN4", 1, "1")
ChangePinName("CONN4", 4, "4")
ChangePinName("CONN4", 2, "2")
ElementList(Need,"CONN5","JUMPER1","IO")
ElementSetAttr("CONN5","device","none")
ElementSetAttr("CONN5","manufacturer","unknown")
ElementSetAttr("CONN5","manufacturer_part_number","unknown")
ElementSetAttr("CONN5","vendor","unknown")
ElementSetAttr("CONN5","vendor_part_number","unknown")
ChangePinName("CONN5", 1, "I/O")
ElementList(Need,"TP9","S1751-46R.fp","S1751-46R")
ElementSetAttr("TP9","device","TESTPOINT")
ElementSetAttr("TP9","manufacturer","unknown")
ElementSetAttr("TP9","manufacturer_part_number","unknown")
ElementSetAttr("TP9","vendor","unknown")
ElementSetAttr("TP9","vendor_part_number","unknown")
ChangePinName("TP9", 1, "1")
ElementList(Need,"TP7","S1751-46R.fp","S1751-46R")
ElementSetAttr("TP7","device","TESTPOINT")
ElementSetAttr("TP7","manufacturer","unknown")
ElementSetAttr("TP7","manufacturer_part_number","unknown")
ElementSetAttr("TP7","vendor","unknown")
ElementSetAttr("TP7","vendor_part_number","unknown")
ChangePinName("TP7", 1, "1")
ElementList(Need,"TP6","S1751-46R.fp","S1751-46R")
ElementSetAttr("TP6","device","TESTPOINT")
ElementSetAttr("TP6","manufacturer","unknown")
ElementSetAttr("TP6","manufacturer_part_number","unknown")
ElementSetAttr("TP6","vendor","unknown")
ElementSetAttr("TP6","vendor_part_number","unknown")
ChangePinName("TP6", 1, "1")
ElementList(Need,"TP8","S1751-46R.fp","S1751-46R")
ElementSetAttr("TP8","device","TESTPOINT")
ElementSetAttr("TP8","manufacturer","unknown")
ElementSetAttr("TP8","manufacturer_part_number","unknown")
ElementSetAttr("TP8","vendor","unknown")
ElementSetAttr("TP8","vendor_part_number","unknown")
ChangePinName("TP8", 1, "1")
ElementList(Need,"TP4","S1751-46R.fp","S1751-46R")
ElementSetAttr("TP4","device","TESTPOINT")
ElementSetAttr("TP4","manufacturer","unknown")
ElementSetAttr("TP4","manufacturer_part_number","unknown")
ElementSetAttr("TP4","vendor","unknown")
ElementSetAttr("TP4","vendor_part_number","unknown")
ChangePinName("TP4", 1, "1")
ElementList(Need,"TP5","S1751-46R.fp","S1751-46R")
ElementSetAttr("TP5","device","TESTPOINT")
ElementSetAttr("TP5","manufacturer","unknown")
ElementSetAttr("TP5","manufacturer_part_number","unknown")
ElementSetAttr("TP5","vendor","unknown")
ElementSetAttr("TP5","vendor_part_number","unknown")
ChangePinName("TP5", 1, "1")
ElementList(Need,"TP2","S1751-46R.fp","S1751-46R")
ElementSetAttr("TP2","device","TESTPOINT")
ElementSetAttr("TP2","manufacturer","unknown")
ElementSetAttr("TP2","manufacturer_part_number","unknown")
ElementSetAttr("TP2","vendor","unknown")
ElementSetAttr("TP2","vendor_part_number","unknown")
ChangePinName("TP2", 1, "1")
ElementList(Need,"R12","1206","49.9")
ElementSetAttr("R12","device","RESISTOR")
ElementSetAttr("R12","manufacturer","unknown")
ElementSetAttr("R12","manufacturer_part_number","unknown")
ElementSetAttr("R12","vendor","unknown")
ElementSetAttr("R12","vendor_part_number","unknown")
ChangePinName("R12", 1, "1")
ChangePinName("R12", 2, "2")
ElementList(Need,"CONN10","AMPHENOL_BNC_31-5431-ver2.fp","unknown")
ElementSetAttr("CONN10","device","BNC")
ElementSetAttr("CONN10","manufacturer","unknown")
ElementSetAttr("CONN10","manufacturer_part_number","unknown")
ElementSetAttr("CONN10","vendor","unknown")
ElementSetAttr("CONN10","vendor_part_number","unknown")
ChangePinName("CONN10", 1, "1")
ChangePinName("CONN10", 2, "2")
ElementList(Need,"C14","rcy(98\, bar-sign)","22uF")
ElementSetAttr("C14","device","POLARIZED_CAPACITOR")
ElementSetAttr("C14","manufacturer","unknown")
ElementSetAttr("C14","manufacturer_part_number","unknown")
ElementSetAttr("C14","vendor","unknown")
ElementSetAttr("C14","vendor_part_number","unknown")
ChangePinName("C14", 2, "-")
ChangePinName("C14", 1, "+")
ElementList(Need,"C13","rcy(98, bar-sign)","22uF")
ElementSetAttr("C13","device","POLARIZED_CAPACITOR")
ElementSetAttr("C13","manufacturer","unknown")
ElementSetAttr("C13","manufacturer_part_number","unknown")
ElementSetAttr("C13","vendor","unknown")
ElementSetAttr("C13","vendor_part_number","unknown")
ChangePinName("C13", 2, "-")
ChangePinName("C13", 1, "+")
ElementList(Need,"C10","0805","10pF")
ElementSetAttr("C10","device","CAPACITOR")
ElementSetAttr("C10","manufacturer","unknown")
ElementSetAttr("C10","manufacturer_part_number","unknown")
ElementSetAttr("C10","vendor","unknown")
ElementSetAttr("C10","vendor_part_number","unknown")
ChangePinName("C10", 2, "2")
ChangePinName("C10", 1, "1")
ElementList(Need,"R10","0805","5K")
ElementSetAttr("R10","device","RESISTOR")
ElementSetAttr("R10","manufacturer","unknown")
ElementSetAttr("R10","manufacturer_part_number","unknown")
ElementSetAttr("R10","vendor","unknown")
ElementSetAttr("R10","vendor_part_number","unknown")
ChangePinName("R10", 1, "1")
ChangePinName("R10", 2, "2")
ElementList(Need,"R11","0805","499")
ElementSetAttr("R11","device","RESISTOR")
ElementSetAttr("R11","manufacturer","unknown")
ElementSetAttr("R11","manufacturer_part_number","unknown")
ElementSetAttr("R11","vendor","unknown")
ElementSetAttr("R11","vendor_part_number","unknown")
ChangePinName("R11", 1, "1")
ChangePinName("R11", 2, "2")
ElementList(Need,"C11","1206","100nF")
ElementSetAttr("C11","device","CAPACITOR")
ElementSetAttr("C11","manufacturer","unknown")
ElementSetAttr("C11","manufacturer_part_number","unknown")
ElementSetAttr("C11","vendor","unknown")
ElementSetAttr("C11","vendor_part_number","unknown")
ChangePinName("C11", 2, "2")
ChangePinName("C11", 1, "1")
ElementList(Need,"C12","1206","100nF")
ElementSetAttr("C12","device","CAPACITOR")
ElementSetAttr("C12","manufacturer","unknown")
ElementSetAttr("C12","manufacturer_part_number","unknown")
ElementSetAttr("C12","vendor","unknown")
ElementSetAttr("C12","vendor_part_number","unknown")
ChangePinName("C12", 2, "2")
ChangePinName("C12", 1, "1")
ElementList(Need,"U10","so(8)","unknown")
ElementSetAttr("U10","device","OPAMP")
ElementSetAttr("U10","manufacturer","unknown")
ElementSetAttr("U10","manufacturer_part_number","unknown")
ElementSetAttr("U10","vendor","unknown")
ElementSetAttr("U10","vendor_part_number","unknown")
ChangePinName("U10", 5, "Null")
ChangePinName("U10", 1, "Null")
ChangePinName("U10", 4, "V-")
ChangePinName("U10", 7, "V+")
ChangePinName("U10", 6, "out")
ChangePinName("U10", 2, "in-")
ChangePinName("U10", 3, "in+")
ElementList(Need,"R21","0805","200K")
ElementSetAttr("R21","device","RESISTOR")
ElementSetAttr("R21","manufacturer","unknown")
ElementSetAttr("R21","manufacturer_part_number","unknown")
ElementSetAttr("R21","vendor","unknown")
ElementSetAttr("R21","vendor_part_number","unknown")
ChangePinName("R21", 1, "1")
ChangePinName("R21", 2, "2")
ElementList(Need,"C22","1206","100nF")
ElementSetAttr("C22","device","CAPACITOR")
ElementSetAttr("C22","manufacturer","unknown")
ElementSetAttr("C22","manufacturer_part_number","unknown")
ElementSetAttr("C22","vendor","unknown")
ElementSetAttr("C22","vendor_part_number","unknown")
ChangePinName("C22", 2, "2")
ChangePinName("C22", 1, "1")
ElementList(Need,"R20","0805","330K")
ElementSetAttr("R20","device","RESISTOR")
ElementSetAttr("R20","manufacturer","unknown")
ElementSetAttr("R20","manufacturer_part_number","unknown")
ElementSetAttr("R20","vendor","unknown")
ElementSetAttr("R20","vendor_part_number","unknown")
ChangePinName("R20", 1, "1")
ChangePinName("R20", 2, "2")
ElementList(Need,"C21","1206","100nF")
ElementSetAttr("C21","device","CAPACITOR")
ElementSetAttr("C21","manufacturer","unknown")
ElementSetAttr("C21","manufacturer_part_number","unknown")
ElementSetAttr("C21","vendor","unknown")
ElementSetAttr("C21","vendor_part_number","unknown")
ChangePinName("C21", 2, "2")
ChangePinName("C21", 1, "1")
ElementList(Need,"C20","2220","1uF")
ElementSetAttr("C20","device","CAPACITOR")
ElementSetAttr("C20","manufacturer","unknown")
ElementSetAttr("C20","manufacturer_part_number","unknown")
ElementSetAttr("C20","vendor","unknown")
ElementSetAttr("C20","vendor_part_number","unknown")
ChangePinName("C20", 2, "2")
ChangePinName("C20", 1, "1")
ElementList(Need,"U20","so(8)","unknown")
ElementSetAttr("U20","device","OPAMP")
ElementSetAttr("U20","manufacturer","unknown")
ElementSetAttr("U20","manufacturer_part_number","unknown")
ElementSetAttr("U20","vendor","unknown")
ElementSetAttr("U20","vendor_part_number","unknown")
ChangePinName("U20", 5, "Trim+")
ChangePinName("U20", 1, "Trim+")
ChangePinName("U20", 4, "V-")
ChangePinName("U20", 7, "V+")
ChangePinName("U20", 6, "out")
ChangePinName("U20", 2, "in-")
ChangePinName("U20", 3, "in+")
ElementList(Need,"C23","1206","100nF")
ElementSetAttr("C23","device","CAPACITOR")
ElementSetAttr("C23","manufacturer","unknown")
ElementSetAttr("C23","manufacturer_part_number","unknown")
ElementSetAttr("C23","vendor","unknown")
ElementSetAttr("C23","vendor_part_number","unknown")
ChangePinName("C23", 2, "2")
ChangePinName("C23", 1, "1")
ElementList(Need,"R41","1206","49.9")
ElementSetAttr("R41","device","RESISTOR")
ElementSetAttr("R41","manufacturer","unknown")
ElementSetAttr("R41","manufacturer_part_number","unknown")
ElementSetAttr("R41","vendor","unknown")
ElementSetAttr("R41","vendor_part_number","unknown")
ChangePinName("R41", 1, "1")
ChangePinName("R41", 2, "2")
ElementList(Need,"R43","1206","1M")
ElementSetAttr("R43","device","RESISTOR")
ElementSetAttr("R43","manufacturer","unknown")
ElementSetAttr("R43","manufacturer_part_number","unknown")
ElementSetAttr("R43","vendor","unknown")
ElementSetAttr("R43","vendor_part_number","unknown")
ChangePinName("R43", 1, "1")
ChangePinName("R43", 2, "2")
ElementList(Need,"R42","1206","1M")
ElementSetAttr("R42","device","RESISTOR")
ElementSetAttr("R42","manufacturer","unknown")
ElementSetAttr("R42","manufacturer_part_number","unknown")
ElementSetAttr("R42","vendor","unknown")
ElementSetAttr("R42","vendor_part_number","unknown")
ChangePinName("R42", 1, "1")
ChangePinName("R42", 2, "2")
ElementList(Need,"C45","1206","0.1uF")
ElementSetAttr("C45","device","CAPACITOR")
ElementSetAttr("C45","manufacturer","unknown")
ElementSetAttr("C45","manufacturer_part_number","unknown")
ElementSetAttr("C45","vendor","unknown")
ElementSetAttr("C45","vendor_part_number","unknown")
ChangePinName("C45", 2, "2")
ChangePinName("C45", 1, "1")
ElementList(Need,"C42","1206","1.0uF")
ElementSetAttr("C42","device","CAPACITOR")
ElementSetAttr("C42","manufacturer","unknown")
ElementSetAttr("C42","manufacturer_part_number","unknown")
ElementSetAttr("C42","vendor","unknown")
ElementSetAttr("C42","vendor_part_number","unknown")
ChangePinName("C42", 2, "2")
ChangePinName("C42", 1, "1")
ElementList(Need,"C46","1206","0.1uF")
ElementSetAttr("C46","device","CAPACITOR")
ElementSetAttr("C46","manufacturer","unknown")
ElementSetAttr("C46","manufacturer_part_number","unknown")
ElementSetAttr("C46","vendor","unknown")
ElementSetAttr("C46","vendor_part_number","unknown")
ChangePinName("C46", 2, "2")
ChangePinName("C46", 1, "1")
ElementList(Need,"C48","rcy(100, bar-sign)","10.0uF")
ElementSetAttr("C48","device","CAPACITOR")
ElementSetAttr("C48","manufacturer","unknown")
ElementSetAttr("C48","manufacturer_part_number","unknown")
ElementSetAttr("C48","vendor","unknown")
ElementSetAttr("C48","vendor_part_number","unknown")
ChangePinName("C48", 2, "2")
ChangePinName("C48", 1, "1")
ElementList(Need,"C47","1206","1.0uF")
ElementSetAttr("C47","device","CAPACITOR")
ElementSetAttr("C47","manufacturer","unknown")
ElementSetAttr("C47","manufacturer_part_number","unknown")
ElementSetAttr("C47","vendor","unknown")
ElementSetAttr("C47","vendor_part_number","unknown")
ChangePinName("C47", 2, "2")
ChangePinName("C47", 1, "1")
ElementList(Need,"C43","1206","1.0uF")
ElementSetAttr("C43","device","CAPACITOR")
ElementSetAttr("C43","manufacturer","unknown")
ElementSetAttr("C43","manufacturer_part_number","unknown")
ElementSetAttr("C43","vendor","unknown")
ElementSetAttr("C43","vendor_part_number","unknown")
ChangePinName("C43", 2, "2")
ChangePinName("C43", 1, "1")
ElementList(Need,"C44","1206","0.1uF")
ElementSetAttr("C44","device","CAPACITOR")
ElementSetAttr("C44","manufacturer","unknown")
ElementSetAttr("C44","manufacturer_part_number","unknown")
ElementSetAttr("C44","vendor","unknown")
ElementSetAttr("C44","vendor_part_number","unknown")
ChangePinName("C44", 2, "2")
ChangePinName("C44", 1, "1")
ElementList(Need,"CONN40","TE_Connectivity_5228686-1-twinax.lht","unknown")
ElementSetAttr("CONN40","device","unknown")
ElementSetAttr("CONN40","manufacturer","unknown")
ElementSetAttr("CONN40","manufacturer_part_number","unknown")
ElementSetAttr("CONN40","vendor","unknown")
ElementSetAttr("CONN40","vendor_part_number","unknown")
ChangePinName("CONN40", 3, "S")
ChangePinName("CONN40", 2, "M")
ChangePinName("CONN40", 1, "F")
ElementList(Need,"C41","rcy(256)","2.2nF")
ElementSetAttr("C41","device","CAPACITOR")
ElementSetAttr("C41","manufacturer","unknown")
ElementSetAttr("C41","manufacturer_part_number","unknown")
ElementSetAttr("C41","vendor","unknown")
ElementSetAttr("C41","vendor_part_number","unknown")
ChangePinName("C41", 2, "2")
ChangePinName("C41", 1, "1")
ElementList(Need,"C40","rcy(256)","2.2nF")
ElementSetAttr("C40","device","CAPACITOR")
ElementSetAttr("C40","manufacturer","unknown")
ElementSetAttr("C40","manufacturer_part_number","unknown")
ElementSetAttr("C40","vendor","unknown")
ElementSetAttr("C40","vendor_part_number","unknown")
ChangePinName("C40", 2, "2")
ChangePinName("C40", 1, "1")
ElementList(Need,"U40","dip(8)","INA121")
ElementSetAttr("U40","device","INA121")
ElementSetAttr("U40","manufacturer","unknown")
ElementSetAttr("U40","manufacturer_part_number","unknown")
ElementSetAttr("U40","vendor","unknown")
ElementSetAttr("U40","vendor_part_number","unknown")
ChangePinName("U40", 3, "+Vin")
ChangePinName("U40", 5, "Inull1")
ChangePinName("U40", 4, "Inull")
ChangePinName("U40", 7, "-Vs")
ChangePinName("U40", 6, "Out")
ChangePinName("U40", 8, "RG2")
ChangePinName("U40", 2, "-Vin")
ChangePinName("U40", 1, "RG1")
ElementList(Need,"TP1","S1751-46R.fp","S1751-46R")
ElementSetAttr("TP1","device","TESTPOINT")
ElementSetAttr("TP1","manufacturer","unknown")
ElementSetAttr("TP1","manufacturer_part_number","unknown")
ElementSetAttr("TP1","vendor","unknown")
ElementSetAttr("TP1","vendor_part_number","unknown")
ChangePinName("TP1", 1, "1")
ElementList(Done)
