Netlist(Freeze)
Netlist(Clear)
Netlist(Add,GND,CONN264-2)
Netlist(Add,unnamed_net3,R201-1)
Netlist(Add,unnamed_net3,R200-2)
Netlist(Add,unnamed_net2,S200-3)
Netlist(Add,unnamed_net2,R200-1)
Netlist(Add,unnamed_net2,CONN221-1)
Netlist(Add,unnamed_net1,R201-2)
Netlist(Add,unnamed_net1,S200-2)
Netlist(Add,unnamed_net1,CONN221-2)
Netlist(Sort)
Netlist(Thaw)
ElementList(Start)
ElementList(Need,"CONN264","connector(2, 1, spacing=100.0mil, silkmark=external)","unknown")
ElementSetAttr("CONN264","device","CONNECTOR_2")
ElementSetAttr("CONN264","manufacturer","unknown")
ElementSetAttr("CONN264","manufacturer_part_number","unknown")
ElementSetAttr("CONN264","vendor","unknown")
ElementSetAttr("CONN264","vendor_part_number","unknown")
ChangePinName("CONN264", 1, "1")
ChangePinName("CONN264", 2, "2")
ElementList(Need,"S200","T101MHAVxx.lht","unknown")
ElementSetAttr("S200","device","unknown")
ElementSetAttr("S200","manufacturer","unknown")
ElementSetAttr("S200","manufacturer_part_number","unknown")
ElementSetAttr("S200","vendor","unknown")
ElementSetAttr("S200","vendor_part_number","unknown")
ChangePinName("S200", 4, "D")
ChangePinName("S200", 2, "C")
ChangePinName("S200", 3, "B")
ChangePinName("S200", 1, "A")
ElementList(Need,"R201","0805","20K")
ElementSetAttr("R201","device","RESISTOR")
ElementSetAttr("R201","manufacturer","unknown")
ElementSetAttr("R201","manufacturer_part_number","unknown")
ElementSetAttr("R201","vendor","unknown")
ElementSetAttr("R201","vendor_part_number","unknown")
ChangePinName("R201", 1, "1")
ChangePinName("R201", 2, "2")
ElementList(Need,"R200","0805","12.7K")
ElementSetAttr("R200","device","RESISTOR")
ElementSetAttr("R200","manufacturer","unknown")
ElementSetAttr("R200","manufacturer_part_number","unknown")
ElementSetAttr("R200","vendor","unknown")
ElementSetAttr("R200","vendor_part_number","unknown")
ChangePinName("R200", 1, "1")
ChangePinName("R200", 2, "2")
ElementList(Need,"CONN221","connector(2, 1, spacing=100.0mil, silkmark=external)","unknown")
ElementSetAttr("CONN221","device","CONNECTOR_2")
ElementSetAttr("CONN221","manufacturer","unknown")
ElementSetAttr("CONN221","manufacturer_part_number","unknown")
ElementSetAttr("CONN221","vendor","unknown")
ElementSetAttr("CONN221","vendor_part_number","unknown")
ChangePinName("CONN221", 1, "1")
ChangePinName("CONN221", 2, "2")
ElementList(Done)
